version: "3.5"

services:
  explorer:
    image: pokt-foundation/explorer
    build:
      context: ${EXPLORER_REPO_PATH}
      dockerfile: ${CWD}/docker/pokt-fdt/dev/Dockerfile.explorer
    command: npm run start
    env_file:
      - ${CWD}/stacks/pokt-fdt/prod-local/.explorer.env
    ports:
      - 4000:4000
    networks:
      - poktnet

  wallet:
    image: pokt-foundation/explorer
    build:
      context: ${EXPLORER_REPO_PATH}
      dockerfile: ${CWD}/docker/pokt-fdt/dev/Dockerfile.wallet
    command: npm run start
    env_file:
      - ${CWD}/stacks/pokt-fdt/prod-local/.wallet.env
    ports:
      - 5000:5000
    networks:
      - poktnet

  portal-api:
    container_name: pokt-fdt-portal-api
    image: pocket-network/gateway
    build:
      context: ${GATEWAY_REPO_PATH}
      dockerfile: ${CWD}/docker/pokt-fdt/dev/Dockerfile
    command: npm run start:watch
    env_file:
      - ${CWD}/stacks/pokt-fdt/prod-local/.portal-api.env
    volumes:
      - "${GATEWAY_REPO_PATH}/src:/usr/src/gateway/src"
      - "${GATEWAY_REPO_PATH}/dist:/usr/src/gateway/dist"
    ports:
      - 3000:3000
    networks:
      - poktnet

  db:
    image: mongo:latest
    env_file:
      - ${CWD}/stacks/pokt-fdt/dev/.db.env
    volumes:
      - ~/.pocket/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - poktnet

  cache:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - poktnet

  metricsdb:
    image: timescale/timescaledb:2.0.2-pg12
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=gatewaydb
    ports:
      - 5432:5432
    networks:
      - poktnet

  node1.dev.pokt:
    networks:
      - poktnet

  node2.dev.pokt:
    networks:
      - poktnet

  node3.dev.pokt:
    networks:
      - poktnet

  node4.dev.pokt:
    networks:
      - poktnet

  node5.pokt:
    networks:
      - poktnet

networks:
  poktnet:
    driver: overlay
