version: "3.5"

services:
  node3.dev.pokt:
    image: poktnetwork/pocket-core:RC-0.9.2-latest-local
    build:
      context: ${POCKET_CORE_REPO_PATH}
      dockerfile: ${CWD}/docker/pokt-net/dev/Dockerfile
    command: "/usr/bin/expect /home/app/.pocket/local_command_dev.sh"
    env_file:
      - ${CWD}/stacks/pokt-net/dev/.node1.env
    environment:
      - DEBUG=${DEBUG}
      - DEBUG_PORT=1234
    ports:
      - "8081:8081"
      - "26657:26657"
    expose:
      - "8081"
      - "26656"
      - "26657"
      - "46656"
      # - "1234"
    volumes:
      - ${CWD}/docker/pokt-net/dev/local_command_dev.sh:/home/app/.pocket/local_command_dev.sh
      - ${CWD}/stacks/pokt-net/shared/chains.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - ${CWD}/stacks/pokt-net/dev/config/config.node1.json:/home/app/.pocket/config/config.json
      - ${CWD}/data/pokt-net.nodea.pokt.dev:/home/app/.pocket/data
      - "${POCKET_CORE_REPO_PATH}:/go/src/github.com/pokt-network/pocket-core"
    networks:
      - poktnet

  node2.dev.pokt:
    image: poktnetwork/pocket-core:RC-0.9.2-latest-local
    build:
      context: ${POCKET_CORE_REPO_PATH}
      dockerfile: ${CWD}/docker/pokt-net/dev/Dockerfile
    command: "/usr/bin/expect /home/app/.pocket/local_command_dev.sh"
    env_file:
      - ${CWD}/stacks/pokt-net/dev/.node2.env
    environment:
      - DEBUG=${DEBUG}
      - DEBUG_PORT=1235
    ports:
      - "8082:8081"
      - "26658:26657"
    expose:
      - "8081"
      - "26656"
      - "26657"
      - "46656"
      - "1235"
    volumes:
      - ${CWD}/docker/pokt-net/dev/local_command_dev.sh:/home/app/.pocket/local_command_dev.sh
      - ${CWD}/stacks/pokt-net/shared/chains.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - ${CWD}/stacks/pokt-net/dev/config/config.node2.json:/home/app/.pocket/config/config.json
      - ${CWD}/data/pokt-net.nodeb.pokt.dev:/home/app/.pocket/data
      - "${POCKET_CORE_REPO_PATH}:/go/src/github.com/pokt-network/pocket-core"
    networks:
      - poktnet

  node3.dev.pokt:
    image: poktnetwork/pocket-core:RC-0.9.2-latest-local
    build:
      context: ${POCKET_CORE_REPO_PATH}
      dockerfile: ${CWD}/docker/pokt-net/dev/Dockerfile
    command: "/usr/bin/expect /home/app/.pocket/local_command_dev.sh"
    env_file:
      - ${CWD}/stacks/pokt-net/dev/.node3.env
    environment:
      - DEBUG=${DEBUG}
      - DEBUG_PORT=1236
    ports:
      - "8083:8081"
      - "26659:26657"
    expose:
      - "8081"
      - "26656"
      - "26657"
      - "46656"
      - "1236"
    volumes:
      - ${CWD}/docker/pokt-net/dev/local_command_dev.sh:/home/app/.pocket/local_command_dev.sh
      - ${CWD}/stacks/pokt-net/shared/chains.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - ${CWD}/stacks/pokt-net/dev/config/config.node3.json:/home/app/.pocket/config/config.json
      - ${CWD}/data/pokt-net.nodec.pokt.dev:/home/app/.pocket/data
      - "${POCKET_CORE_REPO_PATH}:/go/src/github.com/pokt-network/pocket-core"
    networks:
      - poktnet

networks:
  poktnet:
    driver: overlay
    attachable: true
