version: "3.5"

services:
  node1.dev.pokt:
    container_name: node1.dev.pokt
    image: poktnetwork/pocket-core:dev-tm-local
    build:
      context: ${POCKET_CORE_REPOS_PATH}
      dockerfile: ./${POCKET_E2E_STACK_RELATIVE_PATH}/docker/pokt-net/dev-tm/Dockerfile
      args:
        - POCKET_E2E_STACK_RELATIVE_PATH=./${POCKET_E2E_STACK_RELATIVE_PATH}/docker/pokt-net/dev-tm
        - POCKET_CORE_REPO_RELATIVE_PATH=./${POCKET_CORE_REPO_RELATIVE_PATH}
        - POCKET_NETWORK_TENDERMINT_RELATIVE_PATH=./${POCKET_NETWORK_TENDERMINT_RELATIVE_PATH}
    command: "/usr/bin/expect /home/app/local_command_dev.sh"
    env_file:
      - ${CWD}/stacks/pokt-net/dev-tm/.node1.env
    environment:
      - DEBUG=${DEBUG}
      - DEBUG_PORT=1234
    ports:
      - "8081:8081"
      - "26657:26657"
      - "1234:1234"
    expose:
      - "8081"
      - "26656"
      - "26657"
      - "46656"
      # - "1234"
    volumes:
      - ${CWD}/data/pokt-net.node1.data:/home/app/.pocket/data
      - ${CWD}/stacks/pokt-net/dev-tm/config/config.json:/home/app/.pocket/config/config.json
      - ${CWD}/stacks/pokt-net/shared/chains.local.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - "${POCKET_CORE_REPO_PATH}:/go/src/github.com/pokt-network/pocket-core"
      - "${POCKET_NETWORK_TENDERMINT_PATH}:/go/src/github.com/pokt-network/tendermint"
    networks:
      - poktnet

  node2.dev.pokt:
    container_name: node2.dev.pokt
    image: poktnetwork/pocket-core:dev-tm-local
    build:
      context: ${POCKET_CORE_REPOS_PATH}
      dockerfile: ./${POCKET_E2E_STACK_RELATIVE_PATH}/docker/pokt-net/dev-tm/Dockerfile
      args:
        - POCKET_E2E_STACK_RELATIVE_PATH=./${POCKET_E2E_STACK_RELATIVE_PATH}/docker/pokt-net/dev-tm
        - POCKET_CORE_REPO_RELATIVE_PATH=./${POCKET_CORE_REPO_RELATIVE_PATH}
        - POCKET_NETWORK_TENDERMINT_RELATIVE_PATH=./${POCKET_NETWORK_TENDERMINT_RELATIVE_PATH}
    command: "/usr/bin/expect /home/app/local_command_dev.sh"
    env_file:
      - ${CWD}/stacks/pokt-net/dev-tm/.node2.env
    environment:
      - DEBUG=${DEBUG}
      - DEBUG_PORT=1235
    ports:
      - "8082:8081"
      - "26658:26657"
      - "1235:1235"
    expose:
      - "8081"
      - "26656"
      - "26657"
      - "46656"
      - "1235"
    volumes:
      - ${CWD}/data/pokt-net.node2.data:/home/app/.pocket/data
      - ${CWD}/stacks/pokt-net/dev-tm/config/config.json:/home/app/.pocket/config/config.json
      - ${CWD}/stacks/pokt-net/shared/chains.local.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - "${POCKET_CORE_REPO_PATH}:/go/src/github.com/pokt-network/pocket-core"
      - "${POCKET_NETWORK_TENDERMINT_PATH}:/go/src/github.com/pokt-network/tendermint"
    networks:
      - poktnet

  node3.dev.pokt:
    container_name: node3.dev.pokt
    image: poktnetwork/pocket-core:dev-tm-local
    build:
      context: ${POCKET_CORE_REPOS_PATH}
      dockerfile: ./${POCKET_E2E_STACK_RELATIVE_PATH}/docker/pokt-net/dev-tm/Dockerfile
      args:
        - POCKET_E2E_STACK_RELATIVE_PATH=./${POCKET_E2E_STACK_RELATIVE_PATH}/docker/pokt-net/dev-tm
        - POCKET_CORE_REPO_RELATIVE_PATH=./${POCKET_CORE_REPO_RELATIVE_PATH}
        - POCKET_NETWORK_TENDERMINT_RELATIVE_PATH=./${POCKET_NETWORK_TENDERMINT_RELATIVE_PATH}
    command: "/usr/bin/expect /home/app/local_command_dev.sh"
    env_file:
      - ${CWD}/stacks/pokt-net/dev-tm/.node3.env
    environment:
      - DEBUG=${DEBUG}
      - DEBUG_PORT=1236
    ports:
      - "8083:8081"
      - "26659:26657"
      - "1236:1236"
    expose:
      - "8081"
      - "26656"
      - "26657"
      - "46656"
      - "1236"
    volumes:
      - ${CWD}/data/pokt-net.node3.data:/home/app/.pocket/data
      - ${CWD}/stacks/pokt-net/dev-tm/config/config.json:/home/app/.pocket/config/config.json
      - ${CWD}/stacks/pokt-net/shared/chains.local.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - "${POCKET_CORE_REPO_PATH}:/go/src/github.com/pokt-network/pocket-core"
      - "${POCKET_NETWORK_TENDERMINT_PATH}:/go/src/github.com/pokt-network/tendermint"
    networks:
      - poktnet

  node4.dev.pokt:
    container_name: node4.dev.pokt
    image: poktnetwork/pocket-core:dev-tm-local
    build:
      context: ${POCKET_CORE_REPOS_PATH}
      dockerfile: ./${POCKET_E2E_STACK_RELATIVE_PATH}/docker/pokt-net/dev-tm/Dockerfile
      args:
        - POCKET_E2E_STACK_RELATIVE_PATH=./${POCKET_E2E_STACK_RELATIVE_PATH}/docker/pokt-net/dev-tm
        - POCKET_CORE_REPO_RELATIVE_PATH=./${POCKET_CORE_REPO_RELATIVE_PATH}
        - POCKET_NETWORK_TENDERMINT_RELATIVE_PATH=./${POCKET_NETWORK_TENDERMINT_RELATIVE_PATH}
    command: "/usr/bin/expect /home/app/local_command_dev.sh"
    env_file:
      - ${CWD}/stacks/pokt-net/dev-tm/.node4.env
    environment:
      - DEBUG=${DEBUG}
      - DEBUG_PORT=1237
    ports:
      - "8084:8081"
      - "26660:26657"
      - "1237:1237"
    expose:
      - "8081"
      - "26656"
      - "26657"
      - "46656"
      - "1237"
    volumes:
      - ${CWD}/data/pokt-net.node4.data:/home/app/.pocket/data
      - ${CWD}/stacks/pokt-net/dev-tm/config/config.json:/home/app/.pocket/config/config.json
      - ${CWD}/stacks/pokt-net/shared/chains.local.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - "${POCKET_CORE_REPO_PATH}:/go/src/github.com/pokt-network/pocket-core"
      - "${POCKET_NETWORK_TENDERMINT_PATH}:/go/src/github.com/pokt-network/tendermint"
    networks:
      - poktnet

networks:
  poktnet:
    driver: overlay
    attachable: true
