version: "2.1"
services:
  node1.dev.pokt:
    privileged: true
    build:
      context: ${CWD}/docker/pokt-net/prod
      args:
        - BRANCH_NAME=${POCKET_RELEASE_TAG}
    command: /usr/bin/expect /home/app/.pocket/local_command.sh
    ports:
      - 8081:8081
      - 26657:26657
    expose:
      - "8081"
      - "26657"
      - "26656"
      - "46656"
      - "53"
    env_file:
      - ${CWD}/stacks/pokt-net/prod/.node1.env
    networks:
      - pocket
    volumes:
      - ${CWD}/docker/pokt-net/prod/local_command.sh:/home/app/.pocket/local_command.sh
      - ${CWD}/stacks/pokt-net/shared/chains.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - ${CWD}/stacks/pokt-net/prod/config/config.node1.json:/home/app/.pocket/config/config.json
      - ${CWD}/data/pokt-net.node1.dev.pokt:/home/app/.pocket/data

  node2.dev.pokt:
    privileged: true
    build:
      context: ${CWD}/docker/pokt-net/prod
      args:
        - BRANCH_NAME=${POCKET_RELEASE_TAG}
    command: /usr/bin/expect /home/app/.pocket/local_command.sh
    ports:
      - 8082:8081
      - 26658:26657
    expose:
      - "8081"
      - "26657"
      - "26656"
      - "46656"
      - "53"
    env_file:
      - ${CWD}/stacks/pokt-net/prod/.node2.env
    networks:
      - pocket
    volumes:
      - ${CWD}/docker/pokt-net/prod/local_command.sh:/home/app/.pocket/local_command.sh
      - ${CWD}/stacks/pokt-net/shared/chains.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - ${CWD}/stacks/pokt-net/prod/config/config.node2.json:/home/app/.pocket/config/config.json
      - ${CWD}/data/pokt-net.node2.dev.pokt:/home/app/.pocket/data

  node3.dev.pokt:
    privileged: true
    build:
      context: ${CWD}/docker/pokt-net/prod
      args:
        - BRANCH_NAME=${POCKET_RELEASE_TAG}
    command: /usr/bin/expect /home/app/.pocket/local_command.sh
    ports:
      - 8083:8081
      - 26659:26657
    expose:
      - "8081"
      - "26657"
      - "26656"
      - "46656"
      - "53"
    env_file:
      - ${CWD}/stacks/pokt-net/prod/.node3.env
    networks:
      - pocket
    volumes:
      - ${CWD}/docker/pokt-net/prod/local_command.sh:/home/app/.pocket/local_command.sh
      - ${CWD}/stacks/pokt-net/shared/chains.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - ${CWD}/stacks/pokt-net/prod/config/config.node3.json:/home/app/.pocket/config/config.json
      - ${CWD}/data/pokt-net.node3.dev.pokt:/home/app/.pocket/data

  node4.dev.pokt:
    privileged: true
    build:
      context: ${CWD}/docker/pokt-net/prod
      args:
        - BRANCH_NAME=${POCKET_RELEASE_TAG}
    command: /usr/bin/expect /home/app/.pocket/local_command.sh
    ports:
      - 8084:8081
      - 26660:26657
    expose:
      - "8081"
      - "26657"
      - "26656"
      - "46656"
      - "53"
    env_file:
      - ${CWD}/stacks/pokt-net/prod/.node4.env
    networks:
      - pocket
    volumes:
      - ${CWD}/docker/pokt-net/prod/local_command.sh:/home/app/.pocket/local_command.sh
      - ${CWD}/stacks/pokt-net/shared/chains.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - ${CWD}/stacks/pokt-net/prod/config/config.node4.json:/home/app/.pocket/config/config.json
      - ${CWD}/data/pokt-net.node4.dev.pokt:/home/app/.pocket/data

  node5.pokt:
    privileged: true
    build:
      context: ${CWD}/docker/pokt-net/prod
      args:
        - BRANCH_NAME=${POCKET_RELEASE_TAG}
    command: /usr/bin/expect /home/app/.pocket/local_command.sh
    ports:
      - 8085:8081
      - 26661:26657
    expose:
      - "8081"
      - "26657"
      - "26656"
      - "46656"
      - "53"
    env_file:
      - ${CWD}/stacks/pokt-net/prod/.node5.env
    networks:
      - pocket
    volumes:
      - ${CWD}/docker/pokt-net/prod/local_command.sh:/home/app/.pocket/local_command.sh
      - ${CWD}/stacks/pokt-net/shared/chains.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - ${CWD}/stacks/pokt-net/prod/config/config.node5.json:/home/app/.pocket/config/config.json
      - ${CWD}/data/pokt-net.node5.pokt:/home/app/.pocket/data

networks:
  pocket:
    driver: bridge
